services:
  - type: web
    name: ldm4app-backend
    runtime: node
    plan: free
    rootDir: traduttore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
